PRAGMA foreign_keys = ON;

PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS currency_new (
  id BLOB PRIMARY KEY,
  acronym TEXT(3) NOT NULL,
  name TEXT,
  symbol TEXT,
  country_name TEXT,
  country_code TEXT
);

INSERT INTO currency_new (id, acronym, name, country_name, country_code)
SELECT id, acronym, name, country_name, country_code FROM currency;

DROP TABLE currency;
ALTER TABLE currency_new RENAME TO currency;
CREATE UNIQUE INDEX IF NOT EXISTS idx_currency_acronym_unique ON currency(acronym);

PRAGMA foreign_keys = ON;

INSERT INTO currency (id, acronym, name, symbol, country_name, country_code) VALUES
  (lower(hex(randomblob(16))), 'USD', 'United States Dollar', '$', 'United States', 'US'),
  (lower(hex(randomblob(16))), 'EUR', 'Euro', '€', 'Eurozone', 'EU'),
  (lower(hex(randomblob(16))), 'AED', 'United Arab Emirates Dirham', 'د.إ', 'United Arab Emirates', 'AE'),
  (lower(hex(randomblob(16))), 'AFN', 'Afghan Afghani', '؋', 'Afghanistan', 'AF'),
  (lower(hex(randomblob(16))), 'ALL', 'Albanian Lek', 'L', 'Albania', 'AL'),
  (lower(hex(randomblob(16))), 'AMD', 'Armenian Dram', '֏', 'Armenia', 'AM'),
  (lower(hex(randomblob(16))), 'ANG', 'Netherlands Antillean Guilder', 'ƒ', 'Caribbean Netherlands', 'BQ'),
  (lower(hex(randomblob(16))), 'AOA', 'Angolan Kwanza', 'Kz', 'Angola', 'AO'),
  (lower(hex(randomblob(16))), 'ARS', 'Argentine Peso', '$', 'Argentina', 'AR'),
  (lower(hex(randomblob(16))), 'AUD', 'Australian Dollar', 'A$', 'Australia', 'AU'),
  (lower(hex(randomblob(16))), 'AWG', 'Aruban Florin', 'ƒ', 'Aruba', 'AW'),
  (lower(hex(randomblob(16))), 'AZN', 'Azerbaijani Manat', '₼', 'Azerbaijan', 'AZ'),
  (lower(hex(randomblob(16))), 'BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 'Bosnia and Herzegovina', 'BA'),
  (lower(hex(randomblob(16))), 'BBD', 'Barbados Dollar', 'Bds$', 'Barbados', 'BB'),
  (lower(hex(randomblob(16))), 'BDT', 'Bangladeshi Taka', '৳', 'Bangladesh', 'BD'),
  (lower(hex(randomblob(16))), 'BGN', 'Bulgarian Lev', 'лв', 'Bulgaria', 'BG'),
  (lower(hex(randomblob(16))), 'BHD', 'Bahraini Dinar', '.د.ب', 'Bahrain', 'BH'),
  (lower(hex(randomblob(16))), 'BIF', 'Burundian Franc', 'FBu', 'Burundi', 'BI'),
  (lower(hex(randomblob(16))), 'BMD', 'Bermudian Dollar', '$', 'Bermuda', 'BM'),
  (lower(hex(randomblob(16))), 'BND', 'Brunei Dollar', 'B$', 'Brunei', 'BN'),
  (lower(hex(randomblob(16))), 'BOB', 'Bolivian Boliviano', 'Bs', 'Bolivia', 'BO'),
  (lower(hex(randomblob(16))), 'BRL', 'Brazilian Real', 'R$', 'Brazil', 'BR'),
  (lower(hex(randomblob(16))), 'BSD', 'Bahamian Dollar', 'B$', 'Bahamas', 'BS'),
  (lower(hex(randomblob(16))), 'BTN', 'Bhutanese Ngultrum', 'Nu.', 'Bhutan', 'BT'),
  (lower(hex(randomblob(16))), 'BWP', 'Botswana Pula', 'P', 'Botswana', 'BW'),
  (lower(hex(randomblob(16))), 'BYN', 'Belarusian Ruble', 'Br', 'Belarus', 'BY'),
  (lower(hex(randomblob(16))), 'BZD', 'Belize Dollar', 'BZ$', 'Belize', 'BZ'),
  (lower(hex(randomblob(16))), 'CAD', 'Canadian Dollar', 'CA$', 'Canada', 'CA'),
  (lower(hex(randomblob(16))), 'CDF', 'Congolese Franc', 'FC', 'Democratic Republic of the Congo', 'CD'),
  (lower(hex(randomblob(16))), 'CHF', 'Swiss Franc', 'CHF', 'Switzerland', 'CH'),
  (lower(hex(randomblob(16))), 'CLP', 'Chilean Peso', 'CLP$', 'Chile', 'CL'),
  (lower(hex(randomblob(16))), 'CNY', 'Chinese Yuan', '¥', 'China', 'CN'),
  (lower(hex(randomblob(16))), 'COP', 'Colombian Peso', 'CO$', 'Colombia', 'CO'),
  (lower(hex(randomblob(16))), 'CRC', 'Costa Rican Colon', '₡', 'Costa Rica', 'CR'),
  (lower(hex(randomblob(16))), 'CUP', 'Cuban Peso', '₱', 'Cuba', 'CU'),
  (lower(hex(randomblob(16))), 'CVE', 'Cape Verdean Escudo', 'Esc', 'Cape Verde', 'CV'),
  (lower(hex(randomblob(16))), 'CZK', 'Czech Koruna', 'Kč', 'Czechia', 'CZ'),
  (lower(hex(randomblob(16))), 'DJF', 'Djiboutian Franc', 'Fdj', 'Djibouti', 'DJ'),
  (lower(hex(randomblob(16))), 'DKK', 'Danish Krone', 'kr', 'Denmark', 'DK'),
  (lower(hex(randomblob(16))), 'DOP', 'Dominican Peso', 'RD$', 'Dominican Republic', 'DO'),
  (lower(hex(randomblob(16))), 'DZD', 'Algerian Dinar', 'دج', 'Algeria', 'DZ'),
  (lower(hex(randomblob(16))), 'EGP', 'Egyptian Pound', 'E£', 'Egypt', 'EG'),
  (lower(hex(randomblob(16))), 'ERN', 'Eritrean Nakfa', 'Nfk', 'Eritrea', 'ER'),
  (lower(hex(randomblob(16))), 'ETB', 'Ethiopian Birr', 'Br', 'Ethiopia', 'ET'),
  (lower(hex(randomblob(16))), 'FJD', 'Fijian Dollar', 'FJ$', 'Fiji', 'FJ'),
  (lower(hex(randomblob(16))), 'FKP', 'Falkland Islands Pound', '£', 'Falkland Islands', 'FK'),
  (lower(hex(randomblob(16))), 'FOK', 'Faroese Krona', 'kr', 'Faroe Islands', 'FO'),
  (lower(hex(randomblob(16))), 'GBP', 'British Pound Sterling', '£', 'United Kingdom', 'GB'),
  (lower(hex(randomblob(16))), 'GEL', 'Georgian Lari', '₾', 'Georgia', 'GE'),
  (lower(hex(randomblob(16))), 'GGP', 'Guernsey Pound', '£', 'Guernsey', 'GG'),
  (lower(hex(randomblob(16))), 'GHS', 'Ghanaian Cedi', '₵', 'Ghana', 'GH'),
  (lower(hex(randomblob(16))), 'GIP', 'Gibraltar Pound', '£', 'Gibraltar', 'GI'),
  (lower(hex(randomblob(16))), 'GMD', 'Gambian Dalasi', 'D', 'Gambia', 'GM'),
  (lower(hex(randomblob(16))), 'GNF', 'Guinean Franc', 'FG', 'Guinea', 'GN'),
  (lower(hex(randomblob(16))), 'GTQ', 'Guatemalan Quetzal', 'Q', 'Guatemala', 'GT'),
  (lower(hex(randomblob(16))), 'GYD', 'Guyanaese Dollar', 'GY$', 'Guyana', 'GY'),
  (lower(hex(randomblob(16))), 'HKD', 'Hong Kong Dollar', 'HK$', 'Hong Kong', 'HK'),
  (lower(hex(randomblob(16))), 'HNL', 'Honduran Lempira', 'L', 'Honduras', 'HN'),
  (lower(hex(randomblob(16))), 'HRK', 'Croatian Kuna', 'kn', 'Croatia', 'HR'),
  (lower(hex(randomblob(16))), 'HTG', 'Haitian Gourde', 'G', 'Haiti', 'HT'),
  (lower(hex(randomblob(16))), 'HUF', 'Hungarian Forint', 'Ft', 'Hungary', 'HU'),
  (lower(hex(randomblob(16))), 'IDR', 'Indonesian Rupiah', 'Rp', 'Indonesia', 'ID'),
  (lower(hex(randomblob(16))), 'ILS', 'Israeli New Shekel', '₪', 'Israel', 'IL'),
  (lower(hex(randomblob(16))), 'IMP', 'Isle of Man Pound', '£', 'Isle of Man', 'IM'),
  (lower(hex(randomblob(16))), 'INR', 'Indian Rupee', '₹', 'India', 'IN'),
  (lower(hex(randomblob(16))), 'IQD', 'Iraqi Dinar', 'ع.د', 'Iraq', 'IQ'),
  (lower(hex(randomblob(16))), 'IRR', 'Iranian Rial', '﷼', 'Iran', 'IR'),
  (lower(hex(randomblob(16))), 'ISK', 'Icelandic Krona', 'kr', 'Iceland', 'IS'),
  (lower(hex(randomblob(16))), 'JEP', 'Jersey Pound', '£', 'Jersey', 'JE'),
  (lower(hex(randomblob(16))), 'JMD', 'Jamaican Dollar', 'J$', 'Jamaica', 'JM'),
  (lower(hex(randomblob(16))), 'JOD', 'Jordanian Dinar', 'د.ا', 'Jordan', 'JO'),
  (lower(hex(randomblob(16))), 'JPY', 'Japanese Yen', '¥', 'Japan', 'JP'),
  (lower(hex(randomblob(16))), 'KES', 'Kenyan Shilling', 'KSh', 'Kenya', 'KE'),
  (lower(hex(randomblob(16))), 'KGS', 'Kyrgyzstani Som', 'с', 'Kyrgyzstan', 'KG'),
  (lower(hex(randomblob(16))), 'KHR', 'Cambodian Riel', '៛', 'Cambodia', 'KH'),
  (lower(hex(randomblob(16))), 'KID', 'Kiribati Dollar', 'KI$', 'Kiribati', 'KI'),
  (lower(hex(randomblob(16))), 'KMF', 'Comorian Franc', 'CF', 'Comoros', 'KM'),
  (lower(hex(randomblob(16))), 'KRW', 'South Korean Won', '₩', 'South Korea', 'KR'),
  (lower(hex(randomblob(16))), 'KWD', 'Kuwaiti Dinar', 'د.ك', 'Kuwait', 'KW'),
  (lower(hex(randomblob(16))), 'KYD', 'Cayman Islands Dollar', 'CI$', 'Cayman Islands', 'KY'),
  (lower(hex(randomblob(16))), 'KZT', 'Kazakhstani Tenge', '₸', 'Kazakhstan', 'KZ'),
  (lower(hex(randomblob(16))), 'LAK', 'Lao Kip', '₭', 'Laos', 'LA'),
  (lower(hex(randomblob(16))), 'LBP', 'Lebanese Pound', 'ل.ل', 'Lebanon', 'LB'),
  (lower(hex(randomblob(16))), 'LKR', 'Sri Lankan Rupee', 'Rs', 'Sri Lanka', 'LK'),
  (lower(hex(randomblob(16))), 'LRD', 'Liberian Dollar', 'L$', 'Liberia', 'LR'),
  (lower(hex(randomblob(16))), 'LSL', 'Lesotho Loti', 'L', 'Lesotho', 'LS'),
  (lower(hex(randomblob(16))), 'LYD', 'Libyan Dinar', 'ل.د', 'Libya', 'LY'),
  (lower(hex(randomblob(16))), 'MAD', 'Moroccan Dirham', 'د.م.', 'Morocco', 'MA'),
  (lower(hex(randomblob(16))), 'MDL', 'Moldovan Leu', 'L', 'Moldova', 'MD'),
  (lower(hex(randomblob(16))), 'MGA', 'Malagasy Ariary', 'Ar', 'Madagascar', 'MG'),
  (lower(hex(randomblob(16))), 'MKD', 'Macedonian Denar', 'ден', 'North Macedonia', 'MK'),
  (lower(hex(randomblob(16))), 'MMK', 'Myanmar Kyat', 'K', 'Myanmar', 'MM'),
  (lower(hex(randomblob(16))), 'MNT', 'Mongolian Togrog', '₮', 'Mongolia', 'MN'),
  (lower(hex(randomblob(16))), 'MOP', 'Macanese Pataca', 'MOP$', 'Macau', 'MO'),
  (lower(hex(randomblob(16))), 'MRU', 'Mauritanian Ouguiya', 'UM', 'Mauritania', 'MR'),
  (lower(hex(randomblob(16))), 'MUR', 'Mauritian Rupee', '₨', 'Mauritius', 'MU'),
  (lower(hex(randomblob(16))), 'MVR', 'Maldivian Rufiyaa', 'Rf', 'Maldives', 'MV'),
  (lower(hex(randomblob(16))), 'MWK', 'Malawian Kwacha', 'MK', 'Malawi', 'MW'),
  (lower(hex(randomblob(16))), 'MXN', 'Mexican Peso', 'Mex$', 'Mexico', 'MX'),
  (lower(hex(randomblob(16))), 'MYR', 'Malaysian Ringgit', 'RM', 'Malaysia', 'MY'),
  (lower(hex(randomblob(16))), 'MZN', 'Mozambican Metical', 'MT', 'Mozambique', 'MZ'),
  (lower(hex(randomblob(16))), 'NAD', 'Namibian Dollar', 'N$', 'Namibia', 'NA'),
  (lower(hex(randomblob(16))), 'NGN', 'Nigerian Naira', '₦', 'Nigeria', 'NG'),
  (lower(hex(randomblob(16))), 'NIO', 'Nicaraguan Cordoba', 'C$', 'Nicaragua', 'NI'),
  (lower(hex(randomblob(16))), 'NOK', 'Norwegian Krone', 'kr', 'Norway', 'NO'),
  (lower(hex(randomblob(16))), 'NPR', 'Nepalese Rupee', '₨', 'Nepal', 'NP'),
  (lower(hex(randomblob(16))), 'NZD', 'New Zealand Dollar', 'NZ$', 'New Zealand', 'NZ'),
  (lower(hex(randomblob(16))), 'OMR', 'Omani Rial', 'ر.ع.', 'Oman', 'OM'),
  (lower(hex(randomblob(16))), 'PAB', 'Panamanian Balboa', 'B/.', 'Panama', 'PA'),
  (lower(hex(randomblob(16))), 'PEN', 'Peruvian Sol', 'S/', 'Peru', 'PE'),
  (lower(hex(randomblob(16))), 'PGK', 'Papua New Guinean Kina', 'K', 'Papua New Guinea', 'PG'),
  (lower(hex(randomblob(16))), 'PHP', 'Philippine Peso', '₱', 'Philippines', 'PH'),
  (lower(hex(randomblob(16))), 'PKR', 'Pakistani Rupee', '₨', 'Pakistan', 'PK'),
  (lower(hex(randomblob(16))), 'PLN', 'Polish Zloty', 'zł', 'Poland', 'PL'),
  (lower(hex(randomblob(16))), 'PYG', 'Paraguayan Guarani', '₲', 'Paraguay', 'PY'),
  (lower(hex(randomblob(16))), 'QAR', 'Qatari Riyal', 'ر.ق', 'Qatar', 'QA'),
  (lower(hex(randomblob(16))), 'RON', 'Romanian Leu', 'lei', 'Romania', 'RO'),
  (lower(hex(randomblob(16))), 'RSD', 'Serbian Dinar', 'дин', 'Serbia', 'RS'),
  (lower(hex(randomblob(16))), 'RUB', 'Russian Ruble', '₽', 'Russia', 'RU'),
  (lower(hex(randomblob(16))), 'RWF', 'Rwandan Franc', 'FRw', 'Rwanda', 'RW'),
  (lower(hex(randomblob(16))), 'SAR', 'Saudi Riyal', '﷼', 'Saudi Arabia', 'SA'),
  (lower(hex(randomblob(16))), 'SBD', 'Solomon Islands Dollar', 'SI$', 'Solomon Islands', 'SB'),
  (lower(hex(randomblob(16))), 'SCR', 'Seychellois Rupee', '₨', 'Seychelles', 'SC'),
  (lower(hex(randomblob(16))), 'SDG', 'Sudanese Pound', 'ج.س.', 'Sudan', 'SD'),
  (lower(hex(randomblob(16))), 'SEK', 'Swedish Krona', 'kr', 'Sweden', 'SE'),
  (lower(hex(randomblob(16))), 'SGD', 'Singapore Dollar', 'S$', 'Singapore', 'SG'),
  (lower(hex(randomblob(16))), 'SHP', 'Saint Helena Pound', '£', 'Saint Helena', 'SH'),
  (lower(hex(randomblob(16))), 'SLE', 'Sierra Leonean Leone', 'Le', 'Sierra Leone', 'SL'),
  (lower(hex(randomblob(16))), 'SOS', 'Somali Shilling', 'Sh', 'Somalia', 'SO'),
  (lower(hex(randomblob(16))), 'SRD', 'Surinamese Dollar', 'SR$', 'Suriname', 'SR'),
  (lower(hex(randomblob(16))), 'SSP', 'South Sudanese Pound', '£', 'South Sudan', 'SS'),
  (lower(hex(randomblob(16))), 'STN', 'Sao Tome and Principe Dobra', 'Db', 'Sao Tome and Principe', 'ST'),
  (lower(hex(randomblob(16))), 'SYP', 'Syrian Pound', '£', 'Syria', 'SY'),
  (lower(hex(randomblob(16))), 'SZL', 'Eswatini Lilangeni', 'E', 'Eswatini', 'SZ'),
  (lower(hex(randomblob(16))), 'THB', 'Thai Baht', '฿', 'Thailand', 'TH'),
  (lower(hex(randomblob(16))), 'TJS', 'Tajikistani Somoni', 'ЅМ', 'Tajikistan', 'TJ'),
  (lower(hex(randomblob(16))), 'TMT', 'Turkmenistani Manat', 'm', 'Turkmenistan', 'TM'),
  (lower(hex(randomblob(16))), 'TND', 'Tunisian Dinar', 'د.ت', 'Tunisia', 'TN'),
  (lower(hex(randomblob(16))), 'TOP', 'Tongan Paanga', 'T$', 'Tonga', 'TO'),
  (lower(hex(randomblob(16))), 'TRY', 'Turkish Lira', '₺', 'Turkey', 'TR'),
  (lower(hex(randomblob(16))), 'TTD', 'Trinidad and Tobago Dollar', 'TT$', 'Trinidad and Tobago', 'TT'),
  (lower(hex(randomblob(16))), 'TVD', 'Tuvaluan Dollar', 'TV$', 'Tuvalu', 'TV'),
  (lower(hex(randomblob(16))), 'TWD', 'New Taiwan Dollar', 'NT$', 'Taiwan', 'TW'),
  (lower(hex(randomblob(16))), 'TZS', 'Tanzanian Shilling', 'TSh', 'Tanzania', 'TZ'),
  (lower(hex(randomblob(16))), 'UAH', 'Ukrainian Hryvnia', '₴', 'Ukraine', 'UA'),
  (lower(hex(randomblob(16))), 'UGX', 'Ugandan Shilling', 'USh', 'Uganda', 'UG'),
  (lower(hex(randomblob(16))), 'UYU', 'Uruguayan Peso', '$U', 'Uruguay', 'UY'),
  (lower(hex(randomblob(16))), 'UZS', 'Uzbekistani Som', 'so''m', 'Uzbekistan', 'UZ'),
  (lower(hex(randomblob(16))), 'VES', 'Venezuelan Bolivar', 'Bs.', 'Venezuela', 'VE'),
  (lower(hex(randomblob(16))), 'VND', 'Vietnamese Dong', '₫', 'Vietnam', 'VN'),
  (lower(hex(randomblob(16))), 'VUV', 'Vanuatu Vatu', 'VT', 'Vanuatu', 'VU'),
  (lower(hex(randomblob(16))), 'WST', 'Samoan Tala', 'WS$', 'Samoa', 'WS'),
  (lower(hex(randomblob(16))), 'XAF', 'Central African CFA Franc', 'FCFA', 'Central Africa', NULL),
  (lower(hex(randomblob(16))), 'XCD', 'East Caribbean Dollar', 'EC$', 'Eastern Caribbean', NULL),
  (lower(hex(randomblob(16))), 'XOF', 'West African CFA Franc', 'CFA', 'West Africa', NULL),
  (lower(hex(randomblob(16))), 'XPF', 'CFP Franc', 'CFP', 'French Polynesia', 'PF'),
  (lower(hex(randomblob(16))), 'YER', 'Yemeni Rial', '﷼', 'Yemen', 'YE'),
  (lower(hex(randomblob(16))), 'ZAR', 'South African Rand', 'R', 'South Africa', 'ZA'),
  (lower(hex(randomblob(16))), 'ZMW', 'Zambian Kwacha', 'ZK', 'Zambia', 'ZM'),
  (lower(hex(randomblob(16))), 'ZWL', 'Zimbabwean Dollar', 'Z$', 'Zimbabwe', 'ZW'),
  (lower(hex(randomblob(16))), 'BTC', 'Bitcoin', '₿', NULL, NULL)
ON CONFLICT(acronym) DO UPDATE SET
  name = excluded.name,
  symbol = excluded.symbol,
  country_name = excluded.country_name,
  country_code = excluded.country_code;
